# Generated by Django 2.2.3 on 2019-07-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
